[project]
name = "turbopuffer-mcp"
version = "0.1.0"
description = "Turbopuffer MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.9.2",
    "turbopuffer[fast]>=0.4.1",
    "tabulate>=0.9.0",
    "pandas>=2.2.3",
]
